<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.jowen.framework</groupId>
        <artifactId>framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>framework-extras</artifactId>
    <packaging>pom</packaging>

    <description>扩展模块聚合（通用、消息、存储、Web）。</description>

    <modules>
        <module>framework-extras-common</module>
        <module>framework-extras-message</module>
        <module>framework-extras-storage</module>
    </modules>
</project>
